// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC95BE_S1Ys8dbVxfkLc1t1a2ALoVpj_8k',
    appId: '1:502501599012:web:c0cd01f35a1112f0f335b1',
    messagingSenderId: '502501599012',
    projectId: 'dom-app-242fa',
    authDomain: 'dom-app-242fa.firebaseapp.com',
    storageBucket: 'dom-app-242fa.firebasestorage.app',
    measurementId: 'G-BFQ7BXZ66M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXfiadmhsWNudb3Kw0sCb1kg9C95aDqho',
    appId: '1:502501599012:android:5995a6304ca3c09ef335b1',
    messagingSenderId: '502501599012',
    projectId: 'dom-app-242fa',
    storageBucket: 'dom-app-242fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxxHfmzSSpvbSpGIpGOJ6A6Dc1rZHwfLg',
    appId: '1:502501599012:ios:c3ea50682e025690f335b1',
    messagingSenderId: '502501599012',
    projectId: 'dom-app-242fa',
    storageBucket: 'dom-app-242fa.firebasestorage.app',
    iosBundleId: 'com.example.domApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxxHfmzSSpvbSpGIpGOJ6A6Dc1rZHwfLg',
    appId: '1:502501599012:ios:c3ea50682e025690f335b1',
    messagingSenderId: '502501599012',
    projectId: 'dom-app-242fa',
    storageBucket: 'dom-app-242fa.firebasestorage.app',
    iosBundleId: 'com.example.domApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC95BE_S1Ys8dbVxfkLc1t1a2ALoVpj_8k',
    appId: '1:502501599012:web:ca09e7b2a4523d1df335b1',
    messagingSenderId: '502501599012',
    projectId: 'dom-app-242fa',
    authDomain: 'dom-app-242fa.firebaseapp.com',
    storageBucket: 'dom-app-242fa.firebasestorage.app',
    measurementId: 'G-4TLNKBXV0M',
  );

}